#include<bits/stdc++.h>
using namespace std;

int main() {
    unordered_map<int, int> mp;
}
// It cannot store keys in any sorted order, they can be randomized...
// Keys are Uniques...
// Works on O(1)...