#include<bits/stdc++.h>
using namespace std;

int main() {
    int a, b;
    cin >> a >> b;      // Lets Take Input as 3 & 2...
    a = a^b;            // a = 3^2...               => 1...
    b = a^b;            // b = 3^2^2 or 1^2...      => 3...
    a = a^b;            // a = 3^2^3 or 1^3...      => 2...
    cout << a << " " << b << endl;      // a = 2 & b = 3...
}